'use client';

import Link from 'next/link';
import { motion } from 'framer-motion';
import { Music, ArrowLeft } from 'lucide-react';

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-animated-dark">
      {/* Navigation */}
      <nav className="border-b border-white/10 px-6 py-4">
        <div className="max-w-7xl mx-auto flex items-center justify-between">
          <Link href="/" className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-xl bg-gradient-to-br from-cyan-400 to-purple-500 flex items-center justify-center">
              <Music className="w-6 h-6 text-white" />
            </div>
            <span className="font-display font-bold text-xl text-gradient">Karatrack Studio</span>
          </Link>
        </div>
      </nav>

      {/* Content */}
      <main className="max-w-4xl mx-auto px-6 py-12">
        <Link href="/" className="inline-flex items-center gap-2 text-gray-400 hover:text-white mb-8">
          <ArrowLeft className="w-5 h-5" />
          Back to Home
        </Link>

        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          className="glass-panel p-8 md:p-12"
        >
          <h1 className="text-3xl font-bold text-white mb-2">Terms of Service</h1>
          <p className="text-gray-400 mb-8">Last Updated: December 18, 2025</p>

          <div className="prose prose-invert max-w-none space-y-6 text-gray-300">
            <p>
              These Terms of Service ("Terms") govern your access to and use of Karatrack Studio, a software-as-a-service platform provided by Karatrack LLC ("Company", "we", "our", or "us"). By accessing or using Karatrack Studio, you agree to be bound by these Terms. If you do not agree to these Terms, do not use Karatrack Studio.
            </p>

            <h2 className="text-xl font-semibold text-white mt-8 mb-4">1. Service Description</h2>
            <p>
              Karatrack Studio ("Service") is a web-based platform that enables users to process audio files using artificial intelligence, including vocal separation, lyric transcription, and video generation with synchronized scrolling lyrics.
            </p>

            <h2 className="text-xl font-semibold text-white mt-8 mb-4">2. User Eligibility</h2>
            <p>
              There are no specific restrictions on who may use the Service. However, users are responsible for ensuring their compliance with any applicable local laws and regulations regarding the content they process.
            </p>

            <h2 className="text-xl font-semibold text-white mt-8 mb-4">3. Account Registration</h2>
            <p>
              To use the Service, you must create an account. You are responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account. You agree to provide accurate, current, and complete information during the registration process and to update such information as necessary.
            </p>

            <h2 className="text-xl font-semibold text-white mt-8 mb-4">4. Subscription and Credit Model</h2>
            <p>
              The Service operates on a credit-based system. Credits may be obtained through monthly subscription plans or one-time purchases. Different processing options consume varying amounts of credits based on the complexity of the requested operations.
            </p>

            <h2 className="text-xl font-semibold text-white mt-8 mb-4">5. Free Access</h2>
            <p>
              New users receive complimentary credits upon registration to experience the Service. No credit card is required for initial access.
            </p>

            <h2 className="text-xl font-semibold text-white mt-8 mb-4">6. User-Generated Content</h2>
            <p>
              All content generated by users on the platform remains the property of the user. Users bear full responsibility for the use and distribution of their content, including ensuring they have the necessary rights to any audio files they upload. By using the Service, you grant us a non-exclusive, worldwide, royalty-free license to use, store, display, reproduce, modify, and distribute your content solely for the purposes of operating, developing, and improving the Service.
            </p>

            <h2 className="text-xl font-semibold text-white mt-8 mb-4">7. Copyright and Licensing</h2>
            <p>
              The Service does not provide commercial licenses for the content processed or generated. Users are solely responsible for securing any necessary licenses if they wish to use or distribute the processed content for commercial purposes. You represent and warrant that you have all necessary rights to any content you upload to the Service.
            </p>

            <h2 className="text-xl font-semibold text-white mt-8 mb-4">8. Refunds and Cancellations</h2>
            <p>
              Refunds for subscription fees are issued solely in cases of service malfunction. No refunds will be provided for user dissatisfaction with output quality. Users may cancel their subscriptions at any time via the Customer Portal. Due to the nature of AI processing, once credits have been consumed, we do not offer refunds for those credits unless the processing job failed to produce any output. As with all AI-based services, results may vary depending on the quality and characteristics of the input provided by the user.
            </p>

            <h2 className="text-xl font-semibold text-white mt-8 mb-4">9. Payment and Taxes</h2>
            <p>
              Payments and applicable taxes are processed through Stripe, Inc. By providing payment information, you agree to pay all charges incurred through your account at the prices in effect when such charges are incurred. You are responsible for any taxes applicable to your transactions.
            </p>

            <h2 className="text-xl font-semibold text-white mt-8 mb-4">10. Service Availability</h2>
            <p>
              We strive to maintain high availability of the Service but do not provide any specific service level agreements (SLAs) or guarantees regarding uptime or availability.
            </p>

            <h2 className="text-xl font-semibold text-white mt-8 mb-4">11. Limitation of Liability</h2>
            <p>
              To the maximum extent permitted by law, Karatrack LLC shall not be liable for any indirect, incidental, special, consequential, or punitive damages, or any loss of profits or revenues, whether incurred directly or indirectly, or any loss of data, use, goodwill, or other intangible losses, resulting from (a) your use or inability to use the Service; (b) any unauthorized access to or use of our servers and/or any personal information stored therein; (c) any interruption or cessation of transmission to or from the Service; (d) any bugs, viruses, trojan horses, or the like that may be transmitted to or through the Service by any third party; (e) any errors or omissions in any content or for any loss or damage incurred as a result of the use of any content processed through the Service; and/or (f) the defamatory, offensive, or illegal conduct of any third party.
            </p>

            <h2 className="text-xl font-semibold text-white mt-8 mb-4">12. Disclaimer of Warranties</h2>
            <p>
              The Service is provided on an "as is" and "as available" basis. Your use of the Service is at your own risk. The Company makes no representations or warranties of any kind, express or implied, as to the operation of the Service, the accuracy of AI-generated outputs, or the quality of processed content.
            </p>

            <h2 className="text-xl font-semibold text-white mt-8 mb-4">13. Governing Law</h2>
            <p>
              These Terms shall be governed and construed in accordance with the laws of the State of Texas, without regard to its conflict of law provisions.
            </p>

            <h2 className="text-xl font-semibold text-white mt-8 mb-4">14. Changes to Terms</h2>
            <p>
              We reserve the right to modify these Terms at any time. If we make changes, we will provide notice by updating the date at the top of these Terms. By continuing to use the Service after the changes become effective, you agree to be bound by the revised Terms.
            </p>

            <h2 className="text-xl font-semibold text-white mt-8 mb-4">15. Contact Information</h2>
            <p>
              For technical support, please contact: <a href="mailto:support@karatrack.com" className="text-cyan-400 hover:text-cyan-300">support@karatrack.com</a>
            </p>
            <p>
              For administrative or billing inquiries, please contact: <a href="mailto:billing@karatrack.com" className="text-cyan-400 hover:text-cyan-300">billing@karatrack.com</a>
            </p>

            <div className="mt-8 p-4 bg-white/5 rounded-xl">
              <p className="text-gray-400">
                By using Karatrack Studio, you acknowledge that you have read, understood, and agree to be bound by these Terms of Service.
              </p>
            </div>
          </div>
        </motion.div>
      </main>
    </div>
  );
}